apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: university-chatbot-pipeline
spec:
  serialPipeline:
    stages:
    - targetId: prod
      profiles: []
      strategy:
        standard:
          verify: true

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
spec:
  gke:
    cluster: projects/[YOUR_PROJECT_ID]/locations/us-central1-a/clusters/university-chatbot-cluster