apiVersion: v1
kind: Service
metadata:
  name: university-chatbot-service
spec:
  type: LoadBalancer
  selector:
    app: university-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080